import { NextRequest, NextResponse } from "next/server"
import { SESSION_COOKIE, verifySessionToken } from "@/lib/auth"

// Paths that MUST stay public:
// - / (homepage)                 → the public marketing landing (staff use
//                                  /login or /dashboard directly; after sign-in
//                                  the console is the default destination)
// - /login + /api/auth/*          → the login flow itself
// - /api/calls/turn               → voicebot bridge (x-api-key protected inside)
// - /api/calls/status             → Exotel status webhook
// - /api/calls/passthru           → Exotel Passthru applet webhook (delivers RecordingUrl)
// - /form/*, /api/form/*          → the customer-facing loan form
// - /apply, /api/apply            → the public promo/marketing site + its application form
// - /api/whatsapp (POST inbound)  → Meta webhook (HMAC-verified)
// - /api/warmup                   → cron warmup
// - /api/digest                   → scheduled digest email (x-api-key protected inside, see DIGEST.ps1)
// - /api/lead-brain/scan-idle     → scheduled Lead Brain scan (x-api-key protected inside, see lib/scheduler.ts)
// - /api/prompt-tuner/scan        → scheduled Prompt Tuner run (x-api-key protected inside, see lib/scheduler.ts)
const PUBLIC_PREFIXES = [
  "/login",
  "/about",
  "/apply",
  "/promo/",
  "/api/auth/",
  "/form/",
  "/api/form/",
  "/api/apply",
  "/api/warmup",
]

// EXACT matches only — everything else stays session-protected.
// SECURITY: /api/calls (list + trigger outbound), /api/calls/recording
// (Exotel-credentialed audio proxy), and /api/tts are dashboard-only and
// MUST require a login session. Only the two telephony webhooks below and
// the Meta webhook are public.
const PUBLIC_EXACT = [
  "/", // public marketing homepage
  // SEO / social surfaces — crawlers and social bots (facebookexternalhit,
  // Twitterbot) never carry a session, so these must be public or every
  // shared link renders without its preview card and Google can't read
  // the sitemap. Generated by app/robots.ts, app/sitemap.ts and
  // app/opengraph-image.tsx.
  "/robots.txt", "/sitemap.xml", "/opengraph-image",
  "/api/whatsapp", "/api/whatsapp/terminate", "/api/calls/turn", "/api/calls/status", "/api/calls/passthru", "/api/calls/recording/upload", "/api/digest",
  "/api/instagram", // Meta Instagram webhook — HMAC-verified inside
  "/api/system/status", // coarse booleans only — no error details (see route)
  "/api/security/flags", // one boolean, read back by this middleware itself
  "/api/branding", // white-label public branding (public-safe fields only)
  "/api/form-config", // public form schema for customer loan form
  "/api/lead-brain/scan-idle", "/api/prompt-tuner/scan",
]

// ---- IP allowlist (Access Controls toggle) ----
// The toggle lives in Postgres, which Edge middleware can't query — so the
// enabled flag is fetched from /api/security/flags and cached 30s. The
// approved addresses come from the IP_ALLOWLIST env var (comma-separated;
// exact IPs, or prefixes ending in "." for whole ranges). Fail-open when
// the toggle is on but no list is configured — an empty list must never
// lock the admin out.
let _ipFlagCache = false
let _ipFlagAt = 0

// SECURITY (2026-09-20): never derive the self-fetch base URL from the request
// (req.nextUrl.origin comes from the attacker-controlled Host header — an
// attacker sending `Host: evil.com` made the middleware read the allowlist
// flag from THEIR server). Pin it to the configured app URL, or loopback.
async function ipAllowlistEnabled(): Promise<boolean> {
  if (Date.now() - _ipFlagAt < 30_000) return _ipFlagCache
  const base = (process.env.NEXT_PUBLIC_APP_URL || `http://127.0.0.1:${process.env.PORT || 3000}`).replace(/\/$/, "")
  try {
    const res = await fetch(`${base}/api/security/flags`, { cache: "no-store" })
    if (res.ok) {
      _ipFlagCache = !!(await res.json())?.ip_allowlist
      _ipFlagAt = Date.now()
    }
  } catch {
    // flags endpoint unreachable — keep last known value
  }
  return _ipFlagCache
}

function ipAllowed(clientIp: string): boolean {
  const entries = (process.env.IP_ALLOWLIST || "").split(",").map((s) => s.trim()).filter(Boolean)
  if (entries.length === 0) return true
  if (clientIp === "127.0.0.1" || clientIp === "::1") return true
  // Empty/unresolvable IP = no trusted proxy header present → fail closed.
  return entries.some((e) => (e.endsWith(".") ? clientIp.startsWith(e) : clientIp === e))
}

/**
 * SECURITY (2026-09-20): the old code read the FIRST x-forwarded-for entry,
 * which is client-controlled (nginx APPENDS the real address, so a client
 * sending "X-Forwarded-For: 127.0.0.1" bypassed the whole allowlist).
 * Trust order: x-real-ip (overwritten by our nginx) → LAST xff entry (the
 * one our own proxy appended) → "unknown" (fail-closed: not on any list).
 */
function trustedClientIp(req: NextRequest): string {
  const real = (req.headers.get("x-real-ip") || "").trim()
  if (real) return real
  const xff = (req.headers.get("x-forwarded-for") || "").split(",").map((s) => s.trim()).filter(Boolean)
  if (xff.length > 0) return xff[xff.length - 1]
  return "unknown"
}

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl

  // Exact public routes; prefix routes must match at a path boundary
  // ("/apply" no longer lets "/applyanything" through).
  const isPublicPrefix = PUBLIC_PREFIXES.some(
    (p) => pathname === p.replace(/\/$/, "") || pathname.startsWith(p.endsWith("/") ? p : p + "/")
  )
  if (PUBLIC_EXACT.includes(pathname) || isPublicPrefix) {
    return NextResponse.next()
  }

  // Console (session-protected) surface only — webhooks and the customer
  // form above are never IP-restricted.
  if (await ipAllowlistEnabled()) {
    if (!ipAllowed(trustedClientIp(req))) {
      return new NextResponse("Access restricted to approved network ranges.", { status: 403 })
    }
  }

  const session = await verifySessionToken(req.cookies.get(SESSION_COOKIE)?.value)
  if (session) return NextResponse.next()

  // APIs get 401 JSON; pages get redirected to /login.
  if (pathname.startsWith("/api/")) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  }
  const loginUrl = new URL("/login", req.url)
  loginUrl.searchParams.set("next", pathname)
  return NextResponse.redirect(loginUrl)
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico|.*\\.(?:png|jpg|jpeg|svg|webp|ico|css|js|map)$).*)"],
}
